const String dailyCheckList = 'Daily Checklist';
const String leaderBoard = 'Leader Board';
const String dailyJournalEntry = 'Daily Journal Entry';
const String communityWall = 'Community Wall';
const String profile = 'Profile';
const String allCheckList = 'All Checklist';
const String checklistDetails = 'Checklist Details';
const String alldailyJournalEntry = 'All Daily Journal Entry';
const String taskDetails = 'Task Details';
